### ISSUE TITLE
initializing a shift with strings is buggy

### ISSUE THREAD

**Issue by denis-mueller** [jackc/tod#102]
If I create a shift with strings (e.g. `Tod::Shift.new('09:00:00', '11:00:00')`) it works at first sight, but the shift is very buggy (e.g. duration returns 2 because the strings are just casted to int.) 

I had to spent quite a while to figure out the problem. Obviously I understand that Tod::TimeOfDay should be passed instead of strings. 

I see two potential solutions to prevent other people from being confused like I was

a) raise errors when the passed arguments are not of type Tod::TimeOfDay

b) if a string is passed, automatically convert it using Tod::TimeOfDay.parse(param)

**Comment by jackc** [comment]
I can see how that would be confusing.

> I see two potential solutions to prevent other people from being confused like I was
>
> a) raise errors when the passed arguments are not of type Tod::TimeOfDay

That's the most straight forward solution. Kind of goes against the Ruby duck typing way though. The interface is that the argument should respond to `to_i` with the number of seconds since midnight. But I don't think Ruby has any way to specify or enforce that interface.

> b) if a string is passed, automatically convert it using Tod::TimeOfDay.parse(param)

That could be confusing because "8" and 8 would both be accepted but the former would mean 08:00:00 and the later would mean "00:00:08".

---

Maybe a variant on a) would be to call `second_of_day` instead of `to_i`. That would still be loosely / duck typed but would avoid the potential ambiguity.

...

That seemed to work. Fixed in 469c7d81772437c0fdc1c052e3b142a7e87bc770.

**Comment by nathansamson** [comment]
While I understand that the previous (3.1.1) behaviour was not ideal, my code broke as I was passing Time object (actually ActiveSupport::TimeWithTimeZone).

I dont think a upgrade from 3.1.1 to 3.1.2 should break my code...

Maybe be a bit more permissive (at least for the 3.1 or even 3.X branch) and allowing DateTime / Time objects? Eg if responding to strftime use to_i

**Comment by jackc** [comment]
@nathansamson To be honest I am surprised passing `Time` / `ActiveSupport::TimeWithTimeZone` seemed to work for you. `to_i` returns the unix time. e.g.

```
[3] pry(main)> Time.current.to_i
=> 1715522258
```

At the very least I would expect that to be buggy when there is a daylight savings time change.
