### ISSUE TITLE
Time of day 24:00 unexpected behaviour

### ISSUE THREAD

**Issue by bluehallu** [jackc/tod#33]
While 24:00 is a valid time according to ISO8601 (meant to be equivalent to 00:00 of the next day), Tod fails to parse it. Even more strange is what will happen if the AR serializer is being used and the value in the database is 24:00. Tod will read it as 00:00 (which is NOT the same). Saving the object later on won't change the DB value to 00:00. This can lead to all sorts of weirdness when executing SQL queries.

**Comment by jackc** [comment]
Unfortunately, Rails automatically converts `24:00` to `00:00` before it gets to the custom serializer dump and load. I've added as much support for `24:00` as I can to Tod as I can in branch `2400hour`. The most I can do for Rails without monkey patching is to detect when it is about to corrupt the time and raise an exception (https://github.com/jackc/tod/blob/2400hour/lib/tod/time_of_day.rb#L181). 

So Tod could support this on its own, but Rails doesn't cooperate. Not sure if I want to merge this branch into master without serialization support...

This issue is was raised years ago to Rails core, but they rejected making any changes -- https://github.com/rails/rails/issues/7125.

**Comment by bluehallu** [comment]
I've commented on the original issue but I'm not sure it will get looked at. Do you agree with my comments there, and if so, do you think it's worth opening a new issue?

**Comment by jackc** [comment]
I think the correct solution is for Rails to allow hooking into the serialization/deserialization process before type conversion to Time. I _think_ that Rails 5 may allow this, but I haven't been following closely.

As far as just serializing to an integer, that seems to be a reasonable word-around for the time being for those who need to handle 24:00.

**Comment by jjb** [comment]
> I think the correct solution is for Rails to allow hooking into the serialization/deserialization process before type conversion to Time. I think that Rails 5 may allow this, but I haven't been following closely.

Anyone know if this happened?

**Comment by aiomaster** [comment]
Hi @jackc,
I took your 24hour branch and merged it with some changes.
https://github.com/jackc/tod/pull/54

I could get the storing and reloading to work.
The trick is, that if rails parses the 24hour with a date "2000-01-01 24:00:00" it sets the time to 00:00:00 but the date is 2000-01-02 and so we can detect that change of the day and construct a 24hour TimeOfDay.

If we dump 24:00:00 to database it gets stored correctly as that.

**Comment by BitOfUniverse** [comment]
Hi @jackc i've made a PR https://github.com/jackc/tod/pull/64 to the fix issue that was introduced in #54, could you review it?

**Comment by jackc** [comment]
I believe this should now be resolved in v3.0.0.
